In [2]:
!pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------- ------------------------- 20.5/60.9 kB 54.8 kB/s eta 0:00:01
     ------------- ------------------------- 20.5/60.9 kB 54.8 kB/s eta 0:00:01
     ------------- ------------------------- 20.5/60.9 kB 54.8 kB/s eta 0:00:01
     ------------------- ------------------- 30.7/60.9 kB 62.4 kB/s eta 0:00:01
     ------------------- ------------------- 30.7/60.9 kB 62.4 kB/s eta 0:00:01
     ----------------


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
x=np.array([1, 2, 3, 4.4])  # Example usage of numpy
print(x)  # Output the numpy array

[1.  2.  3.  4.4]


In [4]:
x=np.array((1, 2, 3, 4.4))  # Example usage of numpy
print(x)  # Output the numpy array

[1.  2.  3.  4.4]


In [5]:
a=np .arange(5)
print(a)  # Output the array created using arange


[0 1 2 3 4]


In [ ]:
a=np.array([1, 2, 3, 4.4])  # Example usage of numpy