In [2]:
!pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------- ------------------------- 20.5/60.9 kB 54.8 kB/s eta 0:00:01
     ------------- ------------------------- 20.5/60.9 kB 54.8 kB/s eta 0:00:01
     ------------- ------------------------- 20.5/60.9 kB 54.8 kB/s eta 0:00:01
     ------------------- ------------------- 30.7/60.9 kB 62.4 kB/s eta 0:00:01
     ------------------- ------------------- 30.7/60.9 kB 62.4 kB/s eta 0:00:01
     ----------------


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
x=np.array([1, 2, 3, 4.4])  # Example usage of numpy
print(x)  # Output the numpy array

[1.  2.  3.  4.4]


In [4]:
x=np.array((1, 2, 3, 4.4))  # Example usage of numpy
print(x)  # Output the numpy array

[1.  2.  3.  4.4]


In [5]:
a=np .arange(5)
print(a)  # Output the array created using arange


[0 1 2 3 4]


In [ ]:
a=np.array([1, 2, 3, 4.4])  # Example usage of numpy

slicing in numpy array

In [5]:
import numpy as np  # Import numpy with an alias
arr1 = np.arange(10)  # Create an array with values from 0 to 9
arr2 = np.arange(12).reshape(3, 4)  # Corrected 'rearange' to 'reshape'
print(arr1)  # Output the first array
print(arr2)  # Output the second array with reshaped dimensions

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
# To slice numpy arrays, use arr2[row_slice, col_slice] syntax
# Example: select rows in reverse order and columns in steps of -3
result = arr2[-1::-2, -1::-3]
print(result)

[[11  8]
 [ 3  0]]


In [17]:
result= arr2[1::, ::2]  # Slicing the array
print(result)  # Output the sliced result

[[ 4  6]
 [ 8 10]]


In [18]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
print(arr2[0, :])
print(arr2[ :0]) 
print(arr2[1:,1:])
print(arr2[::-2,:2:]) # Output the second row of arr2
print()  # Output the original array for reference

[0 1 2 3]
[]
[[ 5  6  7]
 [ 9 10 11]]
[[8 9]
 [0 1]]



3d array slicing

In [27]:
arr3=np.arange(24).reshape( 2,4,3 )  # Create a new array with values from 0 to 11 reshaped to 3 rows and 4 columns
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [33]:
print(arr3[0], end='\n\n')  # Output the first block of arr3

print(arr3[0, 0], end='\n\n')  # Output the first row of the first block

print(arr3[1, :3], end='\n\n')  # Output the first three rows of the second block

print(arr3[0, :2, ::2], end='\n\n')  # Output the first two rows and every second column of the first block

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[0 1 2]

[[12 13 14]
 [15 16 17]
 [18 19 20]]

[[0 2]
 [3 5]]



In [34]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
a1= np.array([1, 2, 3, 4.4])  # Example usage of numpy
a2=np.array((1, 2, 3, 4))  # Example usage of numpy
print(a1)  # Output the numpy array 
 
print(a2.dtype)  # Output the data type of the numpy array
print(a1.dtype)

print(a1.itemsize)
print(a2.itemsize)

# ndim 
print(a1.ndim)
print(a2.ndim)

# shape
  
print(a1.shape)
print(a2.shape)  

[1.  2.  3.  4.4]
int64
float64
8
8
1
1
(4,)
(4,)


numpy arrey funtion

In [38]:
print(np.zeros(10))
print()


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

